sonar.projectKey=Bunzeeeeer_ExpenseIQ
sonar.organization=bunzeeeeer
sonar.sources=.
sonar.exclusions=**/build/**,**/node_modules/**
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
sonar.java.source=11